site_name: ChennaiPY
site_url: https://chennaipy.org/
repo_url: https://github.com/chennaipy

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  hide_site_name: true
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expandable # Make top navigation expandable
    - navigation.index
    - navigation.center
    - navigation.footer
    
    
  font:
    text: 'Roboto'
  palette:
    primary: 'indigo'
    accent: 'indigo'
extra_css:
  - 'css/custom.css'
extra_javascript:
  - 'js/custom.js'
plugins:
  - search
  - awesome-pages  # Automatically generates nav structure
  - blog

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list  # Enables CSS classes in Markdown
  - md_in_html  # Allows raw HTML inside Markdown


extra:
  generator: false

copyright: Text is available under the Creative Commons Attribution-ShareAlike License.
