site_name: ChennaiPY
site_url: https://chennaipy.org/
repo_url: https://github.com/chennaipy

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  hide_site_name: true
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expandable # Make top navigation expandable
    - navigation.index
    - navigation.center
    - navigation.footer
    
    
  font:
    text: 'Roboto'
  palette:
    primary: 'indigo'
    accent: 'indigo'
#extra_css:
#  - css/custom.css
#  - https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/css/patternfly.min.css
#  - https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/css/patternfly-additions.min.css

extra_css:
  - css/custom.css
  
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/js/patternfly.min.js

plugins:
  - search
  - awesome-pages  # Automatically generates nav structure
  - blog

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - attr_list  # Enables CSS classes in Markdown
  - md_in_html  # Allows raw HTML inside Markdown


extra:
  generator: false

copyright: Text is available under the Creative Commons Attribution-ShareAlike License.
